chore(deps): bump phoenix
GothicKit/phoenix-shared-interface pull request #32
Opened 2023-07-26 15:53 UTC by JucanAndreiDaniel

Update Phoenix to the current main branch

2023-07-26 16:57 UTC, lmichaelis commented
We need to either replace the `PxVdf` implementation with the new `phoenix::Vfs` class or allow deprecated symbols for now. I'm removing the old API from phoenix in v2 which I intend to release later this year.

2023-07-26 21:01 UTC, JaXt0r commented
@lmichaelis 

VDF --> VFS. Mostly only renaming. Changes to check closely are inside:
* Vfs.h
* Vfs.cc

2023-07-27 15:12 UTC, lmichaelis requested changes
In addition, please update the phoenix submodule again because [phoenix/bcb47c1](https://github.com/GothicKit/phoenix/commit/bcb47c1b545962efdc205db9494d1d734d1bed11) fixes an issue I introduced in a recent commit which only happens in release builds.

2023-07-27 15:12 UTC, lmichaelis commented on include/phoenix/cffi/Vfs.h
> +PXC_API void pxVfsMountFile(PxVfs* vfs, char const* path);
This should be called `pxVfsMountDisk`

2023-07-27 15:12 UTC, lmichaelis commented on src/Vfs.cc
> +	return RC(PxVfs, new phoenix::Vfs());
This `RC(...)` wrapper is not required since `PxVfs` is already an alias for `phoenix::Vfs`.

2023-07-27 15:48 UTC, JaXt0r commented
Changes implemented. Please recheck.

2023-07-27 16:14 UTC, merged